wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.5
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.8
epoch:
  desc: null
  value: 1000
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.001
